### ISSUE TITLE
Help presenters convert their content into workshopper workshops.

### ISSUE THREAD

**Issue by davidmason** [campjs/campjs-v#1]
> &lt;timoxley> pomke: s1w: just thinking perhaps I could get campjs volunteers like yourselves to help presenters convert their content into workshops.
> &lt;timoxley> like, presenters come up with the ideas and campjs people help get them into a workshop format
> &lt;timoxley> realised a lot of the overhead is in learning how to assemble a workshop
> &lt;timoxley> if I had people already ready with that info we could pump out high quality workshops easier
> ...
> &lt;pomke> What does it mean to turn something into a workshop?
> &lt;pomke> Specifically nodeschool style?
> &lt;pomke> Or just, something that can be participated in
> &lt;timoxley> pomke: e.g. take a talk slide that says you should do X, have a workshop exercise that gets you to do X
> &lt;pomke> We shall turn them into workshop-delivering ninjai
> &lt;timoxley> pomke: that's the idea. I really want campjs to be something more than just a conference
> ...
> &lt;timoxley> nah, more like generating learning resources
> ...
> &lt;timoxley> it'd be awesome if after each conference we had some artifact
> &lt;timoxley> like a book
> &lt;timoxley> that contained chapters on each talk topic
> &lt;timoxley> with interactive exercises

**Comment by timoxley** [comment]
Need volunteers who can help work with presenters to convert their content into nodeschool.io compatible workshops.

Going to push use of https://github.com/timoxley/adventure-map to knock these up fast.

**Comment by davidmason** [comment]
I would like to put my hand up for writing some workshopper code. I will not be at this camp[1], but I can still write some code beforehand if someone wants a hand. I have been meaning to learn how write workshoppers anyway.

[1]: Costs too much to fly down, or maybe it doesn't and I will decide to go anyway, but at the moment my mortgage is too scary.

**Comment by timoxley** [comment]
@davidmason Idea here is we'd be pairing people with workshop creation experience with presenters whom have none. So, let's get you some practice. 

I have an incomplete https://github.com/timoxley/es5-workshop which needs to be converted to use https://github.com/timoxley/adventure-map. That could be a good start.

**Comment by davidmason** [comment]
@timoxley looks like I have a new project for the weekend (for when it is too hot to be in the ceiling getting the insulation finished).

EDIT: looks like there are a bunch of TODO items in there too, so I'll get onto those when the existing content is ported.

**Comment by SomeoneWeird** [comment]
Going to put my hand up for helping too :)

**Comment by bevacqua** [comment]
I'm interested in this. I'm not sure how to approach turning "High Performance Web" slides into an engaging workshop that can stand on its own, and help is definitely appreciated

**Comment by bevacqua** [comment]
For future reference: https://github.com/bevacqua/workshopper-wat
