### ISSUE TITLE
Vegan communal snacks

### ISSUE THREAD

**Issue by AllyG** [campjs/campjs-v#2]
Are there camp attendees who love Pana Chocolate and Zebra Dream Ice cream? 

I'm not local, and not able to eat many of the communal chocolates, muffins, etc. that people bring. 

I am happy to swing money to any Melbourne locals who can do a run to the Pana store for cakes and chocolates, and the Zebra Dream store for ice cream. These are the store locations for Zebra Dream http://zebradream.com/find-a-store/ and these are the locations for Pana Chocolate stores that also sell cakes http://www.panachocolate.com/where-to-buy/

And I invite other people to join in the fun and put some money in the pot - even if not vegan - because the Pana store cakes are legendary!

**Comment by timoxley** [comment]
@AllyG my apologies for not getting back to you sooner, but we can definitely do this.

**Comment by timoxley** [comment]
I'll put a shout-out for vegan snacks into the pre-event email.
